name       : setbfree
version    : 0.8.4
release    : 2
source     :
    - https://github.com/pantherb/setBfree/archive/v0.8.4.tar.gz : ae18fb6fdfd65f8f14cb4fb6fdd1430a27a162df820a74ef2b58ac09440a9abc
license    : GPL-2.0
component  : multimedia.audio
summary    : A DSP Tonewheel Organ emulator.
description: |
    setBfree is a MIDI-controlled, software synthesizer designed to imitate the sound and properties of the electromechanical organs and sound modification devices that brought world-wide fame to the names and products of Laurens Hammond and Don Leslie.
builddeps  :
    - pkgconfig(ftgl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(libpano13)
    - pkgconfig(lv2core)
build      : |
    %make PREFIX=/usr lv2dir=%libdir%/lv2
install    : |
    %make_install PREFIX=/usr lv2dir=%libdir%/lv2
