name       : setbfree
version    : 0.8.11
release    : 4
source     :
    - https://github.com/pantherb/setBfree/archive/v0.8.11.tar.gz : 3c2d78b96c76a0dc218b73fbf18c664a0f41380e284fc7557ef9eff19be15a1f
license    : GPL-2.0
component  : multimedia.audio
summary    : A DSP Tonewheel Organ emulator.
description: |
    setBfree is a MIDI-controlled, software synthesizer designed to imitate the sound and properties of the electromechanical organs and sound modification devices that brought world-wide fame to the names and products of Laurens Hammond and Don Leslie.
builddeps  :
    - pkgconfig(ftgl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(libpano13)
    - pkgconfig(lv2)
build      : |
    %make PREFIX=/usr lv2dir=%libdir%/lv2
install    : |
    %make_install PREFIX=/usr lv2dir=%libdir%/lv2
