name       : setbfree
version    : 0.8.2
release    : 1
source     :
    - https://github.com/pantherb/setBfree/archive/v0.8.2.tar.gz : 8d32ef48b0e99e2a2d6ccb2c49cfefbc548d38aaad5e2a65e03e4c7e4a7f73e3
license    : GPL-2.0
component  : multimedia.audio
summary    : A DSP Tonewheel Organ emulator.
description: |
    setBfree is a MIDI-controlled, software synthesizer designed to imitate the sound and properties of the electromechanical organs and sound modification devices that brought world-wide fame to the names and products of Laurens Hammond and Don Leslie.
builddeps  :
    - pkgconfig(ftgl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(libpano13)
    - pkgconfig(lv2core)
build      : |
    %make PREFIX=/usr lv2dir=%libdir%/lv2
install    : |
    %make_install PREFIX=/usr lv2dir=%libdir%/lv2
